### PR TITLE
Tweetthis button

### PR DESCRIPTION
**Pull request by RMHogervorst**
This is a minimal example of a tweet shortcode, I've given it a custom css in satRdays.css. however I don't know how this fits in the total css. When I tried this out on a different website parts of the css were overridden. I hope you grok how css works so that the button gets a look in the style of satRdays

### CODE REVIEW

**Comment by DaveParr** [comment]
Thanks for the effort. I'm having a look now. Is it possible you could take a screenshot of where this wasn't working and expand a bit more on what you were expecting to see?

**Comment by DaveParr** [comment]
@RMHogervorst I still think this is a great idea. Are you still interested in re-visiting this feature?

**Comment by RMHogervorst** [comment]
I completely forgat about this. I will pick I up this week

**Comment by DaveParr** [comment]
@RMHogervorst thanks a bunch for the continued interest, I'm going to close this PR right now without merge only because (if I've understood how GitHub PR + review process + notifications works), this will keep pinging me each time you pull changes into your branch from the master, even if the work to make the tweet button on your side isn't ready for me to review and merge yet, and I'm hoping that a few people will be getting involved and issuing me PRs this month, which will make this more likely to change under us and just add to noise for me. I hope you understand this reasoning and I'd really love a new PR when this is something that you think is ready to merge in and would like me to actively review.

Very excited to see what you eventually come up with when you're ready for a merge though 👍

**Comment by RMHogervorst** [comment]
Ah I have just updated it so it works. 
Adds an 'ugly' button to the schedule

Which leads to a working tweet intent:
Screenshot 2020-10-12 at 20 49 38

**Comment by DaveParr** [comment]
Haha. Great timing. I'll have to review this later, but thanks for re-opening the PR, I'll try and get this reviewed in a day or so :)

**Comment by RMHogervorst** [comment]
Take whatever time you need! (and I don't mind you closing it either)

**Comment by RMHogervorst** [comment]
Things we could do

* create a nicer button, this one is quite ugly
* add site.params.baseurl to the intent too, (I tried this but haven't been succussful yet)
* Customize text on tweet button from config.toml

**Comment by DaveParr** [comment]
@RMHogervorst I'm vry happy to put this in as is for now, thanks a bunch 💜. 

I also agree with your points about creating a nicer button, and customising the tweet text defaults. For the tweet text specifically that would be useful as we've seen lots of individual events use event specific hastags. I'm not certain I quite follow you on the 'add site.params.baseurl to the intent too, (I tried this but haven't been succussful yet)'. I don't disagree, I just don't understand the issue or the goal well enough.

It would be really great for me if you could open an issue for each of the things you've suggested and include some more detail. Then, if you want to assign yourself to the work go right ahead, otherwise I'll raise it on our upcoming event on Thursday as available for work and see if there are any takers.

Thanks again for putting this together. Loved the concept as soon as you suggested it 👍

**Comment by DaveParr** [comment]
I just added the hacktoberfest label to this PR as I'm happy to have it marked as that if that's of interest to you. Let me know if it hasn't ticked into your count, if you do care about that, and we'll try and work out what I did wrong 😅

**Pull request merged**
