### PR TITLE
Include all the missing assets from hugo-agency-theme

### LINKED ISSUE #25: Check what the `archetypes` folder does in the [`hugo-agency-theme`](https://github.com/digitalcraftsman/hugo-agency-theme) and maybe move it to this theme
Only the items that are not already present and superceded by our own current files should be copied over. 

Hugo has a 'multiple inheritance' style where the base theme, `agency`, gets sourced only when and item in the `satrdays` theme doesn't get sourced.

As per the config of the theme, we should therefore only include assets from `agency` where **_they are not already present in `satrdays`_**

### PR DESCRIPTION
**Pull request by DaveParr**
This work migrates all the remaining assets from hugo-agency-theme to this theme, as hugo-agency-theme is now achived. I understand this to be allowed by the Apache 2.0 license and encouraged behaviour when a repo archived. If anyone knows otherwise/ the original coders ( @digitalcraftsman + @stp-ip )have an issue with this, please let me know and we'll do whatever you need to make this 'correct'.

The intent for future work is to re-organise the partials that I have missused into a far more sane naming convention, and to continue building from them.

@RMHogervorst  I've pinned you as a reviewer for a sanity check as you so kindly helped identify the missing partials. Feel free to decline though, I know we all have lives outside of GitHub +1

Closes #25 #24 #23

Sorry for the previous #35 I had a brain-fart and tried to merge into develop which not having develop be updated to where master was and it was all just a mess. I hope unless GH decides to pull shenanigans this will be a cleaner review.

### CODE REVIEW

**Comment by digitalcraftsman** [comment]
Hello Dave,

I don't have any issues with your plans. It is grteatto see that there is still interest in the theme and that it will be further developed in some form. And I don't see any roadblockers made by the Apache license either. So feel free to proceed.

**Comment by stp-ip** [comment]
+1

**Comment by DaveParr** [comment]
@digitalcraftsman @stp-ip thanks both. Your work was foundational to getting this project bootstrapped into a useful codebase. We're really grateful for your contribution to OS. So far this theme has powered approximately 20 conferences around the world :)

**Review by RMHogervorst — COMMENTED** [review]
Looks good to me!

**Review by RMHogervorst — APPROVED** [review]

**Pull request merged**
